# Generated by Django 5.1.3 on 2024-12-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_store_remove_seller_status_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='decription',
            new_name='description',
        ),
    ]
