# Generated by Django 5.1.3 on 2024-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_decription_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('R', 'Roman'), ('Q', 'Qissa'), ('H', 'Hikoya')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images/'),
        ),
    ]
