# Generated by Django 5.1.3 on 2024-12-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_book_category_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hajmi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='turi',
            field=models.CharField(default='roman', max_length=250),
        ),
    ]
