# Generated by Django 5.1.3 on 2024-12-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('market', "do'kondan"), ('home', 'uydan')], max_length=250)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('process', 'jarayonda'), ('paid', "to'langan")], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('register_certificate', models.FileField(upload_to='')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('expired_date', models.DateTimeField()),
                ('code', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('new', 'yangi'), ('Moderation', 'Moderatsiya'), ('cod_verified', 'kod tasdiqlangan')], default='new', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('process', 'jarayonda'), ('paid', "to'langan"), ('unpaid', "to'lanmagan"), ('cancelled', 'bekor qilingan')], max_length=250)),
                ('comment', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.category')),
                ('images', models.ManyToManyField(to='common.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.user')),
            ],
        ),
    ]
